### ISSUE TITLE
[BeamEffect] Effect involving deleted objects can cause assertion failure crash

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1873]
Steps to reproduce:

1. Start scenario_60_captureFlag.lua.
2. Unpause the game, if paused.
3. Delete or destroy some or all boundary marker buoys (the vertical line of artifacts through 0,0 on the GM screen)
4. Wait

Expected behavior:

Script logic might fail, but the game doesn't crash.

Observed behavior:

The game crashes with an assertion failure.

Debug build output:

```
ERROR: LUA: update: [string "scenario_60_captureFlag.lua"]:2628: attempt to compare nil with number
ERROR: Oh noes! Better find me and put a breakpoint here!
WARN: 

Assertion failure at operator-> (/git/daid/SeriousProton/src/P.h:105), triggered 1 time:
  'ptr'
```

Backtrace:

```gdb
#0  0x000000000054b930 in P<SpaceObject>::operator->() const (this=0x7ffdd3282408)
    at /git/daid/SeriousProton/src/P.h:105
#1  0x000000000078fd01 in BeamEffect::setSource(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>)
     (this=0x2834fe0, source=..., offset=...)
    at /git/daid/EmptyEpsilon/src/spaceObjects/beamEffect.cpp:171
#2  0x0000000000790eb4 in call_details::executeFunctionImpl<BeamEffect, void (BeamEffect::*&)(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>), std::tuple<P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0> >, 0ul, 1ul>(BeamEffect*, void (BeamEffect::*&)(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>), std::tuple<P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0> >&, std::integer_sequence<unsigned long, 0ul, 1ul>)
   
     (obj=0x2834fe0, func=@0x7ffdd32824b0: (void (BeamEffect::*)(BeamEffect * const, P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>)) 0x78fcd4 <BeamEffect::setSource(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>)>, params=std::tuple containing = {...}) at /git/daid/SeriousProton/src/scriptInterfaceMagic.h:460
#3  0x0000000000790f1d in call_details::executeFunction<BeamEffect, void (BeamEffect::*&)(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>), P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0> >(BeamEffect*, void (BeamEffect::*&)(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>), std::tuple<P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0> >&)
     (obj=0x2834fe0, func=@0x7ffdd32824b0: (void (BeamEffect::*)(BeamEffect * const, P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>)) 0x78fcd4 <BeamEffect::setSource(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>)>, params=std::tuple containing = {...}) at /git/daid/SeriousProton/src/scriptInterfaceMagic.h:467
#4  0x0000000000790fbe in call_details::callFunction<BeamEffect, void (BeamEffect::*)(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>), void, P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0> >(lua_State*)
    (L=0x2200fb8) at /git/daid/SeriousProton/src/scriptInterfaceMagic.h:486
#5  0x0000000000791015 in call<BeamEffect, void (BeamEffect::*)(P<SpaceObject>, glm::vec<3, float, (glm::qualifier)0>)>::function(lua_State*) (L=0x2200fb8)
    at /git/daid/SeriousProton/src/scriptInterfaceMagic.h:500
#6  0x0000000000857519 in luaD_precall (L=0x2200fb8, func=0x2757700, nresults=1)
    at /git/daid/SeriousProton/libs/lua/ldo.c:337
#7  0x000000000086f7bb in luaV_execute (L=0x2200fb8)
    at /git/daid/SeriousProton/libs/lua/lvm.c:1084
#8  0x00000000008579b8 in luaD_call (L=0x2200fb8, func=0x2757680, nResults=0, allowyield=0)
    at /git/daid/SeriousProton/libs/lua/ldo.c:422
#9  0x0000000000850b15 in f_call (L=0x2200fb8, ud=0x7ffdd3282d00)
    at /git/daid/SeriousProton/libs/lua/lapi.c:919
#10 0x0000000000856be3 in luaD_rawrunprotected (L=0x2200fb8, f=0x850ade <f_call>, ud=0x7ffdd3282d00)
    at /git/daid/SeriousProton/libs/lua/ldo.c:142
#11 0x0000000000858162 in luaD_pcall (L=0x2200fb8, func=0x850ade <f_call>, u=0x7ffdd3282d00, old_top=32, ef=0)
    at /git/daid/SeriousProton/libs/lua/ldo.c:644
#12 0x0000000000850bdb in lua_pcallk (L=0x2200fb8, nargs=1, nresults=0, errfunc=0, ctx=0, k=0x0)
    at /git/daid/SeriousProton/libs/lua/lapi.c:945
#13 0x00000000004bd947 in ScriptObject::update(float) (this=0x23013d0, delta=0.0166516993)
    at /git/daid/SeriousProton/src/scriptInterface.cpp:417
#14 0x00000000004239f9 in Engine::runMainLoop() (this=0x15f9b40)
    at /git/daid/SeriousProton/src/engine.cpp:163
#15 0x000000000053fc01 in main(int, char**) (argc=3, argv=0x7ffdd3285bc8)
    at /git/daid/EmptyEpsilon/src/main.cpp:399
```

The scenario populates a table, `boundary_items`, with `Artifact` objects, then fires a `BeamEffect`  between buoys on a timer in the update loop:

```lua
if buoy_beam_timer < 0 then
  for i=1,#boundary_items - 2 do
    if i % 4 == buoy_beam_count % 4 then
      BeamEffect():setSource(boundary_items[i],0,0,0):setTarget(boundary_items[i+2],0,0):setDuration(buoy_beam_interval):setRing(false):setTexture(boundary_beam_string[math.random(1,#boundary_beam_string)])
    ...
```

Deleting an Artifact causes an object to "fire" the beam effect ~~from or~~ at an object that no longer exists, causing the assertion failure.

**Comment by oznogon** [comment]
[This scenario script gist](https://gist.github.com/oznogon/683eb012a2a8e73bba061ad1f385bb30) reliably reproduces the crash after several seconds unpaused.

**Comment by oznogon** [comment]
The patch in #1874 prevents the reproduction gist from failing.

**Comment by daid** [comment]
Note that this only crashes in debug builds. Release builds don't crash due to how the P<> pointers work.
